# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YYKitTest' do

end

target 'YYKitTestTests' do

end

target 'YYKitTestUITests' do

end

pod 'YYKit', '1.0.7'
